[project]
name = "whatpeoplewant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.15",
    "exospherehost==0.0.7b9",
    "openai>=1.100.2",
    "pymongo>=4.14.0",
    "python-dotenv>=1.1.1",
]
